openapi: 3.0.0
info:
  title: LLM Document Query API
  version: 1.0.0
paths:
  /api/documents/upload:
    post:
      summary: Upload a document
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Document uploaded
  /api/query:
    post:
      summary: Process a query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
      responses:
        '200':
          description: Query processed